#pragma checksum "..\..\..\prf_managment.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "0C26EF14C8AEC8E57DBA8FE49E96311FAC2D2CC0"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using StudentManagement;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace StudentManagement {
    
    
    /// <summary>
    /// prf_managment
    /// </summary>
    public partial class prf_managment : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 18 "..\..\..\prf_managment.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid datagrid;
        
        #line default
        #line hidden
        
        
        #line 20 "..\..\..\prf_managment.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox cin_in;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\..\prf_managment.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox prenom_in;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\prf_managment.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox nom_in;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\prf_managment.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ajouter_btn;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\prf_managment.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button supprimer_btn;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\prf_managment.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button update_btn;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\..\prf_managment.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button search_btn;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "7.0.12.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/StudentManagement;component/prf_managment.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\prf_managment.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "7.0.12.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 16 "..\..\..\prf_managment.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.return_btn);
            
            #line default
            #line hidden
            return;
            case 2:
            
            #line 17 "..\..\..\prf_managment.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.logout_btn);
            
            #line default
            #line hidden
            return;
            case 3:
            this.datagrid = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 4:
            this.cin_in = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            this.prenom_in = ((System.Windows.Controls.TextBox)(target));
            return;
            case 6:
            this.nom_in = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.ajouter_btn = ((System.Windows.Controls.Button)(target));
            
            #line 25 "..\..\..\prf_managment.xaml"
            this.ajouter_btn.Click += new System.Windows.RoutedEventHandler(this.ajouter_btn_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.supprimer_btn = ((System.Windows.Controls.Button)(target));
            
            #line 26 "..\..\..\prf_managment.xaml"
            this.supprimer_btn.Click += new System.Windows.RoutedEventHandler(this.supprimer_btn_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.update_btn = ((System.Windows.Controls.Button)(target));
            
            #line 27 "..\..\..\prf_managment.xaml"
            this.update_btn.Click += new System.Windows.RoutedEventHandler(this.update_btn_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            this.search_btn = ((System.Windows.Controls.Button)(target));
            
            #line 28 "..\..\..\prf_managment.xaml"
            this.search_btn.Click += new System.Windows.RoutedEventHandler(this.search_btn_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

